packages:
  - apps/*
  - packages/*

catalog:
  '@stylexjs/stylex': 0.19.0
  '@stylexjs/unplugin': 0.19.0

allowBuilds:
  '@scarf/scarf': false
  electron: true
  electron-winstaller: true
  esbuild: true
  koffi: true
  protobufjs: false

disallowWorkspaceCycles: true

overrides:
  multer@2.2.0: 2.4.0
  undici@6.28.0: 6.28.1
  undici@8.10.1: 8.10.2

patchedDependencies:
  extract-zip@2.0.1: patches/extract-zip@2.0.1.patch
