packages:
  - apps/*
  - packages/*

allowBuilds:
  '@scarf/scarf': false
  electron: true
  electron-winstaller: true
  esbuild: true
  koffi: true
  protobufjs: false

disallowWorkspaceCycles: true
