import { writeFileSync } from 'node:fs'
import iconv from 'iconv-lite'

// Hangul syllables are contiguous in CP949; keep them out of the lookup table.
const characters = []
for (let code = 0x80; code <= 0xffff; code++) {
  if (code >= 0xac00 && code <= 0xd7a3) {
    continue
  }
  const character = String.fromCharCode(code)
  const bytes = iconv.encode(character, 'cp949')
  if (bytes.length === 2 && iconv.decode(bytes, 'cp949') === character) {
    characters.push(character)
  }
}

const chunks = []
for (let offset = 0; offset < characters.length; offset += 64) {
  chunks.push(JSON.stringify(characters.slice(offset, offset + 64).join('')))
}
writeFileSync(
  new URL('../src/cp949-characters.ts', import.meta.url),
  '// Generated by pnpm generate:cp949 from iconv-lite 0.7.3 (MIT).\n' +
    '// Do not edit manually. See notices/iconv-lite-LICENSE.\n' +
    'export const cp949Characters =\n  ' +
    chunks.join(' +\n  ') +
    '\n'
)
