// Shared error codes keep capture, IPC sanitization and recovery UI in agreement.
export const DEVELOPER_ERROR_CODES = {
  NOT_ALLOWED: 'DEVELOPER_NOT_ALLOWED',
  INVALID_COMMAND: 'DEVELOPER_INVALID_COMMAND',
  DISABLED: 'DEVELOPER_DISABLED',
  STORAGE_UNAVAILABLE: 'DEVELOPER_STORAGE_UNAVAILABLE',
  SAMPLE_NOT_FOUND: 'DEVELOPER_SAMPLE_NOT_FOUND',
  CAPTURE_UNAVAILABLE: 'DEVELOPER_CAPTURE_UNAVAILABLE',
  HOTKEY_UNAVAILABLE: 'DEVELOPER_HOTKEY_UNAVAILABLE',
  ADMIN_REQUIRED: 'DEVELOPER_ADMIN_REQUIRED',
  GAME_NOT_FOREGROUND: 'DEVELOPER_GAME_NOT_FOREGROUND',
  PARTY_SLOTS_NOT_FOUND: 'DEVELOPER_PARTY_SLOTS_NOT_FOUND',
  GAME_NOT_FOUND: 'DEVELOPER_GAME_NOT_FOUND',
  PARTICIPANT_WINDOW_NOT_FOUND: 'DEVELOPER_PARTICIPANT_WINDOW_NOT_FOUND',
  PARTICIPANT_WINDOW_UNCERTAIN: 'DEVELOPER_PARTICIPANT_WINDOW_UNCERTAIN',
  OPERATION_FAILED: 'DEVELOPER_OPERATION_FAILED'
} as const
